/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.GerenciadorDoacao;
import Entidades.Doacao;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo Bento
 */
public class Abas extends javax.swing.JFrame {

    /**
     * Creates new form Abas
     */
    public Abas() {
        initComponents();
        ImageIcon logo = new ImageIcon("src/Imagens/icone.png");
        setIconImage(logo.getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        removerFunc = new javax.swing.JButton();
        atualizarFunc = new javax.swing.JButton();
        consultaFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        triagem = new javax.swing.JButton();
        consultaDoador = new javax.swing.JButton();
        cadastraDoador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        consultaDoacoes = new javax.swing.JButton();
        graficoDoacoes = new javax.swing.JButton();
        estoque = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(425, 358));
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 430));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(420, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 430));
        jPanel1.setLayout(null);

        removerFunc.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        removerFunc.setText("Remover Funcionario");
        removerFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerFuncActionPerformed(evt);
            }
        });
        jPanel1.add(removerFunc);
        removerFunc.setBounds(190, 70, 200, 40);

        atualizarFunc.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        atualizarFunc.setText("Atualizar Funcionario");
        atualizarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(atualizarFunc);
        atualizarFunc.setBounds(190, 120, 200, 40);

        consultaFunc.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        consultaFunc.setText("Consultar Funcionario");
        consultaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaFuncActionPerformed(evt);
            }
        });
        jPanel1.add(consultaFunc);
        consultaFunc.setBounds(190, 20, 200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Doacao_de_sangue_de_sangue__entenda_quando_a_ajuda_e_impossivel_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 317);

        jTabbedPane1.addTab("Funcionario", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 430));
        jPanel2.setLayout(null);

        triagem.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        triagem.setText("Triagem");
        triagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triagemActionPerformed(evt);
            }
        });
        jPanel2.add(triagem);
        triagem.setBounds(190, 70, 200, 40);

        consultaDoador.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        consultaDoador.setText("Consultar Doador");
        consultaDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDoadorActionPerformed(evt);
            }
        });
        jPanel2.add(consultaDoador);
        consultaDoador.setBounds(190, 120, 200, 40);

        cadastraDoador.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cadastraDoador.setText("Cadastrar Doador");
        cadastraDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraDoadorActionPerformed(evt);
            }
        });
        jPanel2.add(cadastraDoador);
        cadastraDoador.setBounds(190, 20, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Doacao_de_sangue_de_sangue__entenda_quando_a_ajuda_e_impossivel_1.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 317);

        jTabbedPane1.addTab("Doação", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 430));
        jPanel3.setLayout(null);

        consultaDoacoes.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        consultaDoacoes.setText("Consultar Doações");
        consultaDoacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDoacoesActionPerformed(evt);
            }
        });
        jPanel3.add(consultaDoacoes);
        consultaDoacoes.setBounds(190, 70, 200, 40);

        graficoDoacoes.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        graficoDoacoes.setText("Grafico de doações");
        graficoDoacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficoDoacoesActionPerformed(evt);
            }
        });
        jPanel3.add(graficoDoacoes);
        graficoDoacoes.setBounds(190, 120, 200, 40);

        estoque.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        estoque.setText("Estoque");
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jPanel3.add(estoque);
        estoque.setBounds(190, 20, 200, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Doacao_de_sangue_de_sangue__entenda_quando_a_ajuda_e_impossivel_1.jpg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 317);

        jTabbedPane1.addTab("Controle de Estoque", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerFuncActionPerformed
        RemoveFunc tela = new RemoveFunc();
        tela.setVisible(true);
    }//GEN-LAST:event_removerFuncActionPerformed

    private void atualizarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarFuncActionPerformed
        AtualizaFunc tela = new AtualizaFunc();
        tela.setVisible(true);
    }//GEN-LAST:event_atualizarFuncActionPerformed

    private void consultaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFuncActionPerformed
        ConsultarFunc tela = new ConsultarFunc();
        tela.setVisible(true);
    }//GEN-LAST:event_consultaFuncActionPerformed

    private void triagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triagemActionPerformed
        Triagem tela = new Triagem();
        tela.setVisible(true);
    }//GEN-LAST:event_triagemActionPerformed

    private void consultaDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDoadorActionPerformed
        ConsultarDoador tela = new ConsultarDoador();
        tela.setVisible(true);
    }//GEN-LAST:event_consultaDoadorActionPerformed

    private void cadastraDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraDoadorActionPerformed
        CadastroDoador tela = new CadastroDoador();
        tela.setVisible(true);
    }//GEN-LAST:event_cadastraDoadorActionPerformed

    private void consultaDoacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDoacoesActionPerformed
        File log = new File("C:/logs/log.txt");

        if (log.exists()) {
            //infelizmente a preguiça me fez fazer isso, nao queria criar outra tela so pra pegar o nome do cara
            String nome = JOptionPane.showInputDialog(null, "Informe o nome do doador");
            GerenciadorDoacao gd = new GerenciadorDoacao();
            if (!(nome == null)) {
                if (!nome.equals("")) {
                    List<Doacao> lista = gd.listar();

                    StringBuilder stb = new StringBuilder("");

                    for (Doacao doc : lista) {
                        if (nome.equals(doc.getNome())) {
                            stb.append(" " + doc.getCpf() + ": " + doc.getHora() + " - " + doc.getData() + "\n");
                        }
                    }

                    if (stb.toString().equals("")) {
                        JOptionPane.showMessageDialog(null, "nenhuma doação foi realizada por este doador");
                    } else {
                        //JOptionPane.showMessageDialog(null, stb);
                        DadosDoacao dd = new DadosDoacao();
                        dd.setDoacoes(stb.toString());
                        dd.setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Digite o nome do doador!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "não foram feitas doações ainda", "Ops!", JOptionPane.ERROR_MESSAGE);
            log.delete();
        }
    }//GEN-LAST:event_consultaDoacoesActionPerformed

    private void graficoDoacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficoDoacoesActionPerformed
        ChartPage chart;
        try {
            chart = new ChartPage();
            chart.setVisible(true);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_graficoDoacoesActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        List<Doacao> lista = new ArrayList<>();
        GerenciadorDoacao gd = new GerenciadorDoacao();
        lista = gd.listar();
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não possui nenhuma doação cadastrada",
                    "Mensagem de Erro !", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] titulos = {"Id", "Nome", "Tipo Sanguineo", "Data"};
            int size = lista.size();
            System.out.println(size);
            String[][] matriz = new String[size][4];
            for (int i = 0; i < size; i++) {
                matriz[i][0] = lista.get(i).getId();
                matriz[i][1] = lista.get(i).getNome();
                matriz[i][2] = lista.get(i).getTipoSanguineo();
                matriz[i][3] = lista.get(i).getData();
            }
            DefaultTableModel modelo = new DefaultTableModel(matriz, titulos);
            ControleEstoque tela = new ControleEstoque();
            tela.setVisible(true);
            tela.tabela(modelo);
        }
    }//GEN-LAST:event_estoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarFunc;
    private javax.swing.JButton cadastraDoador;
    private javax.swing.JButton consultaDoacoes;
    private javax.swing.JButton consultaDoador;
    private javax.swing.JButton consultaFunc;
    private javax.swing.JButton estoque;
    private javax.swing.JButton graficoDoacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton removerFunc;
    private javax.swing.JButton triagem;
    // End of variables declaration//GEN-END:variables
}
